version: '3'

services:
  web:
    build: .
    ports:
      - 3333:3333
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      - db
      - db_test
    command: npm run dev

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo

  db_test:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
